export type SchoolDataTypes = {
      website: String,
      dataS20 : String,
      dataS21 : String,
      departmentID : String,
      departmentNameThai : String,
      provinceNameThai : String,
      schoolTypeName : String,
      schoolID : String,
      subDistrictNameThai : String,
      districtNameThai : String,
      postcode : String,
      houseID : String,
      houseNumber : String,
      villageNumber : String,
      trok : String,
      soi : String,
      street : String,
      telephone1 : String,
      telephone2 : String,
      fax : String,
      email : String,
}